name: CloudLaunch CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~
          rm -rf cloudlaunch
          git clone https://github.com/falco1-plk/cloudlaunch.git
          cd cloudlaunch
          docker stop cloudlaunch || true
          docker rm cloudlaunch || true
          docker build -t cloudlaunch-app .
          docker run -d -p 3000:3000 --name cloudlaunch cloudlaunch-app